# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [2]:
!pip install Numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [4]:
data = np.array([1,2,3,4,5])
print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [9]:
# exercise 1.4
arr = np.array([10,20,30,40,50])
print(arr)
arr1 = np.array([[10,20,30], [40,50,60]])
print(arr1)
arr2 = np.array([10, 20,30,40])
print(arr2[0])
arr3 = np.array([1,2,3,4,5,6,7])
print(arr3[1:5])
arr4 = np.array([30,20,40,10])
print(np.sort(arr4))
arr5 = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr5))

[10 20 30 40 50]
[[10 20 30]
 [40 50 60]]
10
[2 3 4 5]
[10 20 30 40]
['berry' 'kiwi' 'pear']


In [10]:
# exercise 1.5 Find the indexes where the value is 9:
arr = np.array([3, 2, 14, 9, 10, 12])
index = np.where(arr == 9)[0]
print(index)

[3]


In [12]:
# Exercise 1.6 Join two arrays given below and print the result.
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[ 9  5  8 55 89 76]
